use crate::models::StaticData;

#[derive(Debug)]
pub enum ShipType {
    NotAvailable,
    Reserved,
    WingInGroundAllTypes,
    WingInGroundHazardousA,
    WingInGroundHazardousB,
    WingInGroundHazardousC,
    WingInGroundHazardousD,
    WingInGroundReserved,
    Fishing,
    Towing,
    TowingLengthExceedsParameters,
    DredgingOrUnderwaterOps,
    DivingOps,
    MilitaryOps,
    Sailing,
    PleasureCraft,
    HighSpeedCraftAllTypes,
    HighSpeedCraftHazardousA,
    HighSpeedCraftHazardousB,
    HighSpeedCraftHazardousC,
    HighSpeedCraftHazardousD,
    HighSpeedReserved,
    HighSpeedNoAdditionalInfo,
    Pilot,
    SearchAndResue,
    Tug,
    PortTender,
    AntiPollutionEquipment,
    LawEnforcement,
    SpareLocalVessel,
    MedicalTransport,
    NoncombatantShip,
    PassengerAllTypes,
    PassengerAllTypesHazardousA,
    PassengerAllTypesHazardousB,
    PassengerAllTypesHazardousC,
    PassengerAllTypesHazardousD,
    PassengerReserved,
    PassengerNoAdditionalInfo,
    CargoAllTypes,
    CargoHazardousA,
    CargoHazardousB,
    CargoHazardousC,
    CargoHazardousD,
    CargoReserved,
    CargoNoAdditionalInfo,
    TankerAllTypes,
    TankerHazardousA,
    TankerHazardousB,
    TankerHazardousC,
    TankerHazardousD,
    TankerReserved,
    TankerNoAdditionalInfo,
    OtherTypeAllTypes,
    OtherTypeHazardousA,
    OtherTypeHazardousB,
    OtherTypeHazardousC,
    OtherTypeHazardousD,
    OtherTypeReserved,
    OtherTypeNoAdditionalInfo,
}

impl StaticData {
    #[inline(always)]
    pub fn ship_type_text(&self) -> ShipType {
        ship_type_text(self.ship_type)
    }
}

pub fn ship_type_text(ship_type: u8) -> ShipType {
    match ship_type {
        1..=19 => ShipType::Reserved,
        20 => ShipType::WingInGroundAllTypes,
        21 => ShipType::WingInGroundHazardousA,
        22 => ShipType::WingInGroundHazardousB,
        23 => ShipType::WingInGroundHazardousC,
        24 => ShipType::WingInGroundHazardousD,
        25..=29 => ShipType::WingInGroundReserved,
        30 => ShipType::Fishing,
        31 => ShipType::Towing,
        32 => ShipType::TowingLengthExceedsParameters,
        33 => ShipType::DredgingOrUnderwaterOps,
        34 => ShipType::DivingOps,
        35 => ShipType::MilitaryOps,
        36 => ShipType::Sailing,
        37 => ShipType::PleasureCraft,
        38..=39 => ShipType::Reserved,
        40 => ShipType::HighSpeedCraftAllTypes,
        41 => ShipType::HighSpeedCraftHazardousA,
        42 => ShipType::HighSpeedCraftHazardousB,
        43 => ShipType::HighSpeedCraftHazardousC,
        44 => ShipType::HighSpeedCraftHazardousD,
        45..=48 => ShipType::HighSpeedReserved,
        49 => ShipType::HighSpeedNoAdditionalInfo,
        50 => ShipType::Pilot,
        51 => ShipType::SearchAndResue,
        52 => ShipType::Tug,
        53 => ShipType::PortTender,
        54 => ShipType::AntiPollutionEquipment,
        55 => ShipType::LawEnforcement,
        56..=57 => ShipType::SpareLocalVessel,
        58 => ShipType::MedicalTransport,
        59 => ShipType::NoncombatantShip,
        60 => ShipType::PassengerAllTypes,
        61 => ShipType::PassengerAllTypesHazardousA,
        62 => ShipType::PassengerAllTypesHazardousB,
        63 => ShipType::PassengerAllTypesHazardousC,
        64 => ShipType::PassengerAllTypesHazardousD,
        65..=68 => ShipType::PassengerReserved,
        69 => ShipType::PassengerNoAdditionalInfo,
        70 => ShipType::CargoAllTypes,
        71 => ShipType::CargoHazardousA,
        72 => ShipType::CargoHazardousB,
        73 => ShipType::CargoHazardousC,
        74 => ShipType::CargoHazardousD,
        75..=78 => ShipType::CargoReserved,
        79 => ShipType::CargoNoAdditionalInfo,
        80 => ShipType::TankerAllTypes,
        81 => ShipType::TankerHazardousA,
        82 => ShipType::TankerHazardousB,
        83 => ShipType::TankerHazardousC,
        84 => ShipType::TankerHazardousD,
        85..=88 => ShipType::TankerReserved,
        89 => ShipType::TankerNoAdditionalInfo,
        90 => ShipType::OtherTypeAllTypes,
        91 => ShipType::OtherTypeHazardousA,
        92 => ShipType::OtherTypeHazardousB,
        93 => ShipType::OtherTypeHazardousC,
        94 => ShipType::OtherTypeHazardousD,
        95..=98 => ShipType::OtherTypeReserved,
        99 => ShipType::OtherTypeNoAdditionalInfo,
        _ => ShipType::NotAvailable,
    }
}