[package]
name = "ais_rs"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "multipart_decoding"
harness = false

[[bench]]
name = "single_part_decoding"
harness = false